.github/workflows/robot_ci.yml
README.md
commands/arcadeDrive.py
commands/tankDrive.py
requirements.txt
robot.py
robots/greenBot.py
subsystems/drivetrains/westcoast.py

This is minimally done into main just to get things working At this point, only GreenBot SHOULD work
Issue: #34 
1. Ran the sim and didn't break
2. Deployed to Green bot and didn't break
Started with @tuffinmuffin 's robot.py and copied code in until it worked again
Start with command vs magic bot

fix: Took Nathans Command code and merged it

---

robot_requirements.txt

Nathan needed the robot_requirements from his original MR
Nathan asked...

fix: 🐛 Bring back robot_requirements.txt

---

README.md

Updated README.md to talk about how and what to update firmware on
Nobody understood firmware or labeling. Hopefully this starts to fix it.

docs: ✏️ Added documentation around firmware to README

---

README.md
subsystems/actuators/dumboArm.py
subsystems/drivetrains/westcoast.py
utils/componentUtils.py
utils/hardwareFactory.py
utils/sensorFactory.py

Changed a misspelling for component
Spelling matters

style: 💄 spelling changes for component

---

robots/dumboBot.py

1. Ensure ~/robotConfig doesn't exist or attempting to run dumbo bot
2. Run python robot.py sim
3. See a stack trace that may not be obvious that the robotConfig needs added/fixed
Attempt to literally spell out the problem with the missing/bad robotConfig
Just wrapped the subsystem assignments in a try block to throw an informative exception
Few people understand why the bot is crashing. Trying to make it more obvious.

style: 💄 Simple change to dumbo to throw error if bad config

---

Input.py
robots/dumboBot.py
robots/greenBot.py

#59
Test the button values and what they return and how often they return.
We need an input system to get different types of input in a much cleaner way.
I am making this change to fix the getButton method, so it returns a more useful value.

Fixing Input System

---

robots/dumboBot.py

Use multiple controllers to test the different functions of the robot.
Making this change so there are enough joysticks to control the robot.

added multiple controllers

---

subsystems/arm/grader.py

mutiple speed by 12 for intake

---

robots/dumboBot.py
subsystems/arm/grader.py

Fix grabber input

---

auto.py
robots/dumboBot.py
subsystems/actuators/dumboArm.py

change angle from 90 to 62

---

commands/breadbox/armCommands.py
configs/subsystems/breadboxArmRotation.yml
robots/breadboxBot.py
subsystems/actuators/breadboxArmRotation.py

calibration mode
button updates
Issue: #100 
Drove on the field

fix: bug fixes from robot

---

robots/breadboxBot.py

enabled camera server

---

configs/subsystems/breadboxArmController.yml
robot_requirements.txt
robots/breadboxBot.py

feat: Add Camera Server

---

CODEOWNERS

Updated for competition season so we can slow down to speed up
Mentors need to be involved in merges now.
We want to ensure the best quality code for the drive team.

Update CODEOWNERS to mentors merge main only

---

input.py

Remove Slew on joysticks

---

commands/tankDrive.py
robots/breadboxBot.py

Hold right trigger on the driver controller and see the change in speeds.
Drive team wants a way to limit their speed when a button is pressed to allow them to more easily get more precise movement.

Limit robot speed

---

auto.py

✅ Closes: #130
Issue: #130 
None of course
Don't want to drive past
Need to drive shorter and it's all hardcoded
Because Olagappan said so

refactor: 💡 Now do 8

---

auto.py
robots/breadboxBot.py

feat: add auto driver configuration

---

auto.py
commands/tankDrive.py
robots/breadboxBot.py

Fix l: presit cal vals gor auto

---

robots/breadboxBot.py
subsystems/actuators/breadboxArmController.py
subsystems/actuators/breadboxArmRotation.py

Finsished when postition
moved telemetry fro arm rotation to perdioc

feat: added command generator for arm

---

configs/subsystems/breadboxArmController.yml

1. Run on the robot and test the angles to check for functionality.
Drive team asked for updates to angles.
This changes was made so we can do more functions, like picking up cones.

Updated arm angles
